import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { Poppins } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import { dark } from '@clerk/themes'

const font = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800']
})


export const metadata: Metadata = {
  title: 'Estream',
  description: 'Generated by create next app',
  icons: '/estream-color.svg'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{baseTheme: dark}}>
      <html lang="en">
        <head>

        </head>
        <body className={font.className}>
          <ThemeProvider
          attribute='class'
          forcedTheme='dark'
          storageKey='estream-theme'>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
